# Use the official lightweight Python image
FROM python:3.10-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install webapp2
RUN pip install webapp2

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Run main.py when the container launches
CMD ["gunicorn", "-b", "0.0.0.0:8080", "main:app"]
